controller_type: CARTESIAN_VELOCITY

is_delta: false

traj_interpolator_cfg:
  traj_interpolator_type: COSINE_CARTESIAN_VELOCITY
  time_fraction: 0.3

action_scale:
  translation: 1.0
  rotation: 1.0

state_estimator_cfg:
  is_estimation: false
  state_estimator_type: EXPONENTIAL_SMOOTHING
  alpha_q: 0.9
  alpha_dq: 0.9
  alpha_eef: 1.0
  alpha_eef_vel: 1.0
