CONTROL:
        SAFETY:
                MAX_TORQUE: 10 # org 5
                MIN_TORQUE: -10 # org -5
                MAX_TRANS_SPEED: 0.1
                MIN_TRANS_SPEED: -0.1
                MAX_ROT_SPEED: 0.1
                MIN_ROT_SPEED: -0.1
