# Data Collection Configuration
dataset_name: "demos_collected"
obs_cfg: "configs/real_robot_observation_cfg.yml"
robot: "xarm6"
ip: "192.168.1.235"
controller_type: "cartsian_servo_position"
max_steps: 15000
control_frequency: 50
save2memory_first: true
FT_option: true
cam_necessary: true
demo_save_frequency: 10